version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - type: shell
        command: bundle exec rake