jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '3.0'
      - run: echo "Ruby 2.7 has been installed"
orbs:
  ruby: circleci/ruby@latest
version: 2.1